"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:48:53.085208+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, to_date, lit, broadcast
from pyspark.sql.types import StructType, StructField, StringType, FloatType, TimestampType, IntegerType
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Define schema for Bronze layer
    bronze_schema = StructType([
        StructField("customer_id", StringType(), True),
        StructField("transaction_id", StringType(), True),
        StructField("transaction_date", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("payment_method", StringType(), True),
        StructField("status", StringType(), True),
        StructField("product_id", StringType(), True)
    ])
    
    # Read CSV files into DataFrame
    bronze_df = spark.read.schema(bronze_schema).csv(input_path)
    
    # Add metadata columns
    bronze_df = bronze_df.withColumn("ingestion_timestamp", current_timestamp()) \
                         .withColumn("source_file", input_path) \
                         .withColumn("pipeline_run_id", lit(run_id))
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(FloatType())) \
                        .withColumn("transaction_date", to_date(col("transaction_date"), "yyyy-MM-dd"))
    
    # Partition by transaction_date and write as Parquet
    bronze_df.write.partitionBy("transaction_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning
    bronze_df = spark.read.parquet(bronze_path).where(col("transaction_date") == run_date)
    
    # Filter out NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id, keeping the latest ingestion_timestamp
    bronze_df = bronze_df.withColumn("rank", max("ingestion_timestamp").over(window.partitionBy("transaction_id"))) \
                         .filter(col("rank") == col("ingestion_timestamp")) \
                        .drop("rank")
    
    # Read merchants data and broadcast hint
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    
    # Join with merchants on merchant_id
    silver_df = bronze_df.join(merchants_df, bronze_df.product_id == merchants_df.merchant_id, "left")
    
    # Add quality_flag column
    null_customer_id_count = bronze_df.filter(col("customer_id").isNull()).count()
    total_rows = bronze_df.count()
    quality_halt_threshold = 0.05  # 5%
    
    if null_customer_id_count / total_rows > quality_halt_threshold:
        silver_df = silver_df.withColumn("quality_flag", lit("UNMATCHED"))
        silver_df.write.json(f"s3://your-bucket/run_metadata/run_metadata_{run_date}.json")
        raise Exception("Quality halt threshold exceeded. Pipeline aborted.")
    
    silver_df = silver_df.withColumn("quality_flag", lit("CLEAN"))
    
    # Write Silver Parquet partitioned by date
    silver_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = SparkSession.builder.appName("ChurnRiskPipeline").getOrCreate()
    
    # Define paths and run details
    input_path = "s3://your-bucket/bronze/transactions/"
    bronze_path = "s3://your-bucket/bronze/transactions/"
    merchants_path = "s3://your-bucket/dimensions/merchants/"
    output_path = "s3://your-bucket/silver/transactions/"
    run_date = "2023-10-01"
    run_id = "12345"
    
    # Execute Bronze and Silver stages
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, expr, to_date, sum, count, collect_set, first, broadcast, when
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, LongType, DoubleType, TimestampType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    run_metadata = {}
    
    try:
        build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
        build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
        build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
        
        run_metadata['status'] = 'SUCCESS'
    except Exception as e:
        run_metadata['status'] = 'FAILURE'
        run_metadata['error'] = str(e)
    
    spark.createDataFrame([(run_metadata,)], ['metadata']).write.mode('overwrite').json(f"{gold_output_dir}/run_metadata_{run_date}.json")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver_df = spark.read.parquet(silver_path).where(col("transaction_date") >= expr(f"date_sub(current_date, 30)"))
    
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", to_date(col("transaction_date")).alias("date")) \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    merchant_performance_df.repartition("date").write.mode('overwrite').partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    silver_df = spark.read.parquet(silver_path).where(col("status") == "COMPLETED")
    
    customer_ltv_df = silver_df.groupBy("customer_id") \
        .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            first("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            collect_set("payment_method").alias("payment_methods")
        )
    
    customer_ltv_df = customer_ltv_df.withColumn("avg_txn_value", col("total_spent") / col("total_txns"))
    customer_ltv_df = customer_ltv_df.withColumn("preferred_payment_method", expr("transform(payment_methods, x -> x)[pos(array_max(payment_methods), 1)]"))
    
    customer_ltv_df.write.mode('overwrite').parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    silver_df = spark.read.parquet(silver_path).where(col("transaction_date") >= expr(f"date_sub(current_date, 30)"))
    
    daily_summary_df = silver_df.groupBy(to_date(col("transaction_date")).alias("date")) \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id")).alias("unique_customers"),
            count(col("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    daily_summary_df.repartition("date").write.mode('overwrite').partitionBy("date").parquet(output_path)

def build_churn_risk(spark, silver_path, output_path, run_date):
    silver_df = spark.read.parquet(silver_path).where(col("transaction_date") >= expr(f"date_sub(current_date, 30)"))
    
    customer_rfm_df = silver_df.groupBy("customer_id") \
        .agg(
            max("transaction_date").alias("last_transaction_date"),
            count("*").alias("transaction_frequency"),
            sum("amount").alias("total_spent")
        )
    
    customer_rfm_df = customer_rfm_df.withColumn("recency_days", expr("datediff(current_date, last_transaction_date)"))
    customer_rfm_df = customer_rfm_df.withColumn("risk_status", when(col("recency_days") > 14, 1).otherwise(0))
    customer_rfm_df = customer_rfm_df.withColumn("generated_at", expr("current_date()"))
    
    customer_rfm_df.repartition("customer_id").write.mode('overwrite').parquet(output_path)
