"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:50:38.760389+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import FloatType, StringType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_dedup_df = (transactions_df.orderBy(col("transaction_id"), col("ingestion_timestamp").desc())
                            .dropDuplicates(["transaction_id"]))
    
    # Read merchants data and cache it
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                    .option("inferSchema", "false")
                   .load(merchants_path))
    merchants_df = merchants_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    spark.catalog.cache_table("merchants")
    
    # Enrich: join transactions with merchants on merchant_id
    enriched_df = (transactions_dedup_df.join(broadcast(merchants_df), "merchant_id", "left_outer")
                 .withColumn("quality_flag", when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))
    
    # Write as Parquet partitioned by date
    enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://smitday7-genai/bronze/"
    bronze_path = "s3://smitday7-genai/silver/"
    merchants_path = "s3://smitday7-genai/dimensions/merchants.csv"
    output_path = "s3://smitday7-genai/silver/"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    
    # Transform Silver
    transform_silver(spark, f"{bronze_path}/date={run_date}", merchants_path, f"{output_path}/date={run_date}", run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://smitday7-genai/metadata/run_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, expr, mode, to_date, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType
import json

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build merchant performance table
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    
    # Build customer LTV table
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    
    # Build daily summary table
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata summary to JSON
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables_built": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    with open(f"{gold_output_dir}/run_metadata.json", "w") as f:
        json.dump(run_metadata, f)

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    silver_df = (spark.read.parquet(silver_path)
                 .where(col("date") == run_date)
                 .withColumn("amount", col("amount").cast(FloatType())))
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate metrics
    merchant_performance_df = (completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date")
                             .agg(sum("amount").alias("total_revenue"),
                                   count("*").alias("txn_count")))
    
    # Calculate failure rate
    all_txns = silver_df.groupBy("merchant_id").agg(count("*").alias("total_txns"),
                                                    count(col("status").isin("FAILED")).alias("failed_txns"))
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join metrics and failure rate
    final_df = merchant_performance_df.join(failure_rate_df, on=["merchant_id"], how="left")
    
    # Write to output path
    final_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer transactions data
    silver_df = (spark.read.parquet(silver_path)
                .where(col("status") == "COMPLETED")
                .withColumn("amount", col("amount").cast(FloatType())))
    
    # Calculate LTV metrics
    ltv_df = (silver_df.groupBy("customer_id")
              .agg(sum("amount").alias("total_spent"),
                   count("*").alias("total_txns"),
                   expr("avg(amount)").alias("avg_txn_value"),
                   min("transaction_date").alias("first_txn_date"),
                   max("transaction_date").alias("last_txn_date"),
                   mode("payment_method").over(Window.partitionBy("customer_id")).alias("preferred_payment_method")))
    
    # Write to output path
    ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    silver_df = (spark.read.parquet(silver_path)
                .where(col("date") == run_date)
                .withColumn("amount", col("amount").cast(FloatType())))
    
    # Calculate daily summary metrics
    daily_summary_df = (silver_df.groupBy("date")
                        .agg(sum("amount").alias("total_revenue"),
                             count("*").alias("total_txns"),
                             countDistinct("customer_id").alias("unique_customers"),
                             countDistinct("merchant_id").alias("unique_merchants")))
    
    # Calculate failure rate
    all_txns = silver_df.groupBy("date").agg(count("*").alias("total_txns"),
                                             count(col("status").isin("FAILED")).alias("failed_txns"))
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join metrics and failure rate
    final_df = daily_summary_df.join(failure_rate_df, on=["date"], how="left")
    
    # Write to output path
    final_df.write.partitionBy("date").mode("overwrite").parquet(output_path)
